@AccountService_HostAddress = http://localhost:5033

###

GET {{AccountService_HostAddress}}/api/account/
Accept: application/json

###

PUT {{AccountService_HostAddress}}/api/account/change/1
Accept: application/json
